name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore tools
        run: dotnet tool restore

      - name: Run Build
        run: dotnet build -c Release -maxCpuCount

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*.nupkg
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}

      - name: Push packages
        run: dotnet nuget push "bin/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k  ${{ secrets.NUGET_KEY }} --skip-duplicate
